Obligatorio_P2_MVC/Models/OperadorViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Obligatorio_P2_MVC.Models
{
    public class OperadorViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Contraseña { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Apellido { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Fecha Ingreso")]
        public DateTime FechaIngresoTrabajo { get; set; }

    }
}

Obligatorio_P2_MVC/Controllers/ActividadController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Models;
using System.Reflection;

namespace Obligatorio_P2_MVC.Controllers
{
    public class ActividadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


      //  [Privado(Roles ="huesped, operador")]
        public IActionResult ListarActividadesPorFecha()
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == DateTime.Today)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
            }
            return View(listaActividades);
        }



        [HttpPost]
       // [Privado(Roles = "huesped, operador")]
        public IActionResult ListarActividadesPorFecha(DateTime fecha)
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();           

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == fecha)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
                if (listaActividades.Count == 0)
                {
                    ViewBag.Error = "No hay actividades en esa fecha";
                    
                }
            }
            return View(listaActividades);
        }

    }
}

Obligatorio_P2_MVC/Controllers/OperadorController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Models;
using ObligatorioP2_C_;
using Obligatorio_P2_MVC.Helpers;
using Obligatorio_P2_MVC.Filters;

namespace Obligatorio_P2_MVC.Controllers
{
   [Privado(Roles = "operador")]
    public class OperadorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

       

        public IActionResult ListarDatosOperador(string email)
        {
            var operador = Hostal.Instancia.ObtenerOperadorPorEmail(email);
            OperadorViewModel datosOperador = null;

            if (operador != null && operador.Email == email)
            {
                datosOperador = new OperadorViewModel()
                {
                    Email = operador.Email,
                    Nombre = operador.Nombre,
                    Apellido = operador.Apellido,
                    FechaIngresoTrabajo = operador.FechaIngresoTrabajo
                };
            }

            return View(datosOperador);
        }

        

        public IActionResult ListarAgendaPorFecha()
        {
            Hostal hostal = Hostal.Instancia;
            List<AgendaViewModel> listaAgendas = new List<AgendaViewModel>();

            foreach (var agenda in hostal.ObtenerAgendas())
            {
                if (agenda._actividad.Fecha == DateTime.Today)
                {
                    var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                    listaAgendas.Add(agendaModel);                   
                }
            }

            return View(listaAgendas);
        }



        [HttpPost]
        public IActionResult ListarAgendaPorFecha(DateTime fecha)
        {
            Hostal hostal = Hostal.Instancia;
            List<AgendaViewModel> listaAgendas = new List<AgendaViewModel>();

            foreach (var agenda in hostal.ObtenerAgendas())
            {
                if (agenda._actividad.Fecha == fecha)
                {
                   
                    var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                    listaAgendas.Add(agendaModel);
                }
            }

            return View(listaAgendas);
        }
       
        public IActionResult ListarAgendaHuesped()
        {
            Hostal hostal = Hostal.Instancia;
            List<AgendaViewModel> listaAgendas = new List<AgendaViewModel>();

            foreach (var agenda in hostal.ObtenerAgendas())
            {
                var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);
                if (agendaModel == null)
                {
                    ViewBag.Error = "No hay agendas para mostrar";
                    return View("Index");
                }
                
                listaAgendas.Add(agendaModel);
            }
            return View(listaAgendas);
        }



        [HttpPost]
        public IActionResult ListarAgendaHuesped(TipoDocumento tipoDocumento, string numeroDocumento)
        {
            var listaAgendasHuesped = Hostal.Instancia.AgendasPorHuesped(tipoDocumento, numeroDocumento);

            List<AgendaViewModel> listaAgendas = new List<AgendaViewModel>();

            foreach (var agenda in listaAgendasHuesped)
            {
                if (agenda._huesped._tipoDocumento == tipoDocumento && agenda._huesped.NumeroDocumento == numeroDocumento)
                {                    
                    var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                    listaAgendas.Add(agendaModel);
                }
            }

            return View(listaAgendas);
        }

        
        public IActionResult ConfirmarAgenda(int id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Error al intentar agendar";
                return View("ListarAgendasPendientesPago");
            }
            try
            {
                Hostal.Instancia.ConfirmarEstadoAgenda(id);
                var agenda = Hostal.Instancia.ObtenerAgendaPorId(id);
                var agendaViewModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                return View(agendaViewModel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error al confirmar la agenda: " + ex.Message;
                return View("Error");
            }
        }

        public IActionResult ListarAgendasPendientesPago()
        {
            Hostal hostal = Hostal.Instancia;
            List<AgendaViewModel> listaAgendas = new List<AgendaViewModel>();

            foreach (var agenda in hostal.ObtenerAgendas())
            {
                if (agenda.Estado == EstadoAgenda.PENDIENTE_PAGO)
                {
                    var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                    listaAgendas.Add(agendaModel);
                }
            }

            return View(listaAgendas);
        }







    }
}

Obligatorio_P2_MVC/Controllers/ProveedorController.cs
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Models;
using ObligatorioP2_C_;
using System.Threading;

namespace Obligatorio_P2_MVC.Controllers
{
    [Privado(Roles = "operador")]
    public class ProveedorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListarProveedores()
        {
            Hostal hostal = Hostal.Instancia;
            List<ProveedorViewModel> listaProveedores = new List<ProveedorViewModel>();

            foreach (var proveedor in hostal.ObtenerProveedores())
            {           
               listaProveedores.Add(new ProveedorViewModel() {Nombre = proveedor.NombreProveedor, Telefono = proveedor.Telefono, Direccion = proveedor.Direccion, Descuento = proveedor.Descuento });
               
            }
            return View(listaProveedores);
        }

        public ActionResult AplicarDescuento(string nombre)
        {
            Hostal hostal = Hostal.Instancia;
            Proveedor proveedor = hostal.ObtenerProveedor(nombre);
            ProveedorDescuentoViewModel proveedorModel = new ProveedorDescuentoViewModel() { Nombre = proveedor.NombreProveedor, Descuento = proveedor.Descuento };
            return View(proveedorModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AplicarDescuento(ProveedorDescuentoViewModel model)
        {
            if (!ModelState.IsValid) 
            {
                ViewBag.Error = "Los datos del formulario no son válidos.";
                return View(model);
            }

            try
            {                
                var proveedor = Hostal.Instancia.ObtenerProveedor(model.Nombre);              
                Hostal.Instancia.ActualizarDescuentoProveedor(proveedor, model.Descuento);

                return RedirectToAction("ListarProveedores");

            }
            catch (System.Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(model);
            }
            
        }

       




    }
}

Obligatorio_P2_MVC/Views/Operador/ConfirmarAgenda.cshtml
@model Obligatorio_P2_MVC.Models.AgendaViewModel

@{
    ViewData["Title"] = "Confirmar Agenda";
}

<h1>Confirmar Agenda</h1>

<div>
    
   
    <dl class="row">
        <h3 class="alert-danger">@ViewBag.Error</h3>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Actividad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Actividad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaActividad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaActividad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lugar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostoActividad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostoActividad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDocumento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoDocumento)
        </dd>
        <p>
            <a asp-action="Index" asp-controller="Operador">Volver menú</a>
        </p>
        <p>
            <a asp-action="ListarAgendasPendientesPago" asp-controller="Operador">Volvera lista</a>
        </p>
    </dl>
</div>

Obligatorio_P2_MVC/Views/Operador/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Menú Operador</h1>
<div class="d-flex gap-3 ">
    @Html.ActionLink("Listado de actividades", "ListarActividadesPorFecha", "Actividad", new {email = Context.Session.GetString("email")}, new { @class = "btn btn-primary" })


<a href="@Url.Action("ListarProveedores", "Proveedor")" class="btn btn-primary">Listado de proveedores</a>


@Html.ActionLink("Listar datos Operador", "ListarDatosOperador", "Operador", new {email = Context.Session.GetString("email")}, new { @class = "btn btn-primary" })


<a href="@Url.Action("ListarAgendaPorFecha", "Operador")" class="btn btn-primary">Listar agendas</a>


<a href="@Url.Action("ListarAgendaHuesped", "Operador")" class="btn btn-primary">Listar agendas de huésped</a>


<a href="@Url.Action("ListarAgendasPendientesPago", "Operador")" class="btn btn-primary">Listar agendas pendientes de pago</a>

</div>


    
    
    
   
    
    

Obligatorio_P2_MVC/Views/Operador/ListarAgendaHuesped.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.AgendaViewModel>
@using Obligatorio_P2_MVC.Models
@using ObligatorioP2_C_

@{
    ViewData["Title"] = "Listar Agendas huésped";
}

<h1>ListarAgendaHuesped</h1>
<h3 class="alert-danger">@ViewBag.Error</h3>

<form method="post" action="/Operador/ListarAgendaHuesped">
    <div>
        <input type="radio" id="option1" name="tipoDocumento" value="@TipoDocumento.CI" required>
        <label for="option1">CI</label>
    </div>
    <div>
        <input type="radio" id="option2" name="tipoDocumento" value="@TipoDocumento.PASAPORTE" required>
        <label for="option2">PASAPORTE</label>
    </div>
    <div>
        <input type="radio" id="option3" name="tipoDocumento" value="@TipoDocumento.OTROS" required>
        <label for="option3">OTROS</label>
    </div>
    <div>
        <label for="textInput">Número Documento:</label>
        <input type="text" id="textInput" name="numeroDocumento" required>
    </div>
    <div>
        <input type="submit" value="Búscar">
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Proveedor)
            </th>
           <th>
                @Html.DisplayNameFor(model => model.TipoDocumento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoDocumento)
            </td>
           
        </tr>
}

    </tbody>
</table>
        <p>
            <a asp-action="Index" asp-controller="Operador" class="btn-toolbar">Volver</a>
        </p>

Obligatorio_P2_MVC/Views/Operador/ListarAgendaPorFecha.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.AgendaViewModel>

@{
    ViewData["Title"] = "ListarAgendaPorFecha";
}

<h1>Listar agendas por fecha</h1>
<h3 class="alert-danger">@ViewBag.Error</h3>

<form method="post" action="/Operador/ListarAgendaPorFecha" class="m-lg-auto">
    <label for="fecha">Fecha:</label>
    <input type="date" id="fecha" name="fecha" required>
    <button type="submit" class="btn-primary">Buscar</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proveedor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoActividad)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Proveedor)
                </td>
                

        </tr>
}
    </tbody>
</table>
            <div class="d-inline-flex gap-4" >
                <p>
                    <a asp-action="Index" asp-controller="Operador">Volver a menú</a>
                </p>    

                <p>
                    <a asp-action="ListarAgendaPorFecha" asp-controller="Operador">Volver a lista</a>
                </p>
            </div>

Obligatorio_P2_MVC/Views/Operador/ListarAgendasPendientesPago.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.AgendaViewModel>
@using Obligatorio_P2_MVC.Models
@using ObligatorioP2_C_

@{
    ViewData["Title"] = "ListarAgendasPendientesPago";
}

<h1>Listar agendas pendientes de pago</h1>
<h3 class="alert-danger">@ViewBag.Error</h3>

<h3 class="alert-danger">@ViewBag.Error</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proveedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoDocumento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoDocumento)
            </td>
                <td>
                    @Html.ActionLink("Confirmar Agenda", "ConfirmarAgenda", "Operador", new {IdAgenda =item.Id})
                </td>
        </tr>
}
    </tbody>
</table>
        <p>
            <a asp-action="Index" asp-controller="Operador">Volver menú</a>
        </p>

Obligatorio_P2_MVC/Views/Operador/ListarDatosOperador.cshtml
@model Obligatorio_P2_MVC.Models.OperadorViewModel

@{
    ViewData["Title"] = "ListarDatosOperador";
}

<h1>Listar datos operador</h1>
<h3 class="alert-danger">@ViewBag.Error</h3>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contraseña)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngresoTrabajo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaIngresoTrabajo)
        </dd>
    </dl>
</div>
<div>    
    <a asp-action="Index">Volver</a>
</div>