Obligatorio_P2_MVC/Models/HuespedViewModel.cs
using ObligatorioP2_C_;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Obligatorio_P2_MVC.Models
{
    public class HuespedViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Contraseña { get; set; }
        [Required]
        [DisplayName("Tipo documento")]
        public TipoDocumento TipoDocumento { get; set; }

        [Required]
        [MinLength(8)]
        [MaxLength(8)]
        [DisplayName("Numero documento")]
        public string NumeroDocumento { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        [DisplayName("Habitación")]
        public int Habitacion { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayName("Fecha nacimiento")]
        public DateTime FechaNacimiento { get; set; }
        [DisplayName("Nivel de fidelización")]
        [Range(1, 4)]
        public int NivelFidelizacion { get; set; }


        
    }
}

Obligatorio_P2_MVC/Controllers/ActividadController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Models;
using System.Reflection;

namespace Obligatorio_P2_MVC.Controllers
{
    public class ActividadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


      //  [Privado(Roles ="huesped, operador")]
        public IActionResult ListarActividadesPorFecha()
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == DateTime.Today)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
            }
            return View(listaActividades);
        }



        [HttpPost]
       // [Privado(Roles = "huesped, operador")]
        public IActionResult ListarActividadesPorFecha(DateTime fecha)
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();           

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == fecha)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
                if (listaActividades.Count == 0)
                {
                    ViewBag.Error = "No hay actividades en esa fecha";
                    
                }
            }
            return View(listaActividades);
        }

    }
}

Obligatorio_P2_MVC/Controllers/HuespedController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Helpers;
using Obligatorio_P2_MVC.Models;
using ObligatorioP2_C_;
using System.Security.Cryptography.X509Certificates;

namespace Obligatorio_P2_MVC.Controllers
{
    
    public class HuespedController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
       
        public IActionResult RegistroHuesped()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult RegistroHuesped(HuespedViewModel model)
        {
            Hostal hostal = Hostal.Instancia;
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Los datos ingresados no son válidos";
                return View(model);
            }

            try
            {
                var huesped = new Huesped(model.Email, model.Contraseña, model.TipoDocumento, model.NumeroDocumento, model.Nombre, model.Apellido, model.Habitacion, model.FechaNacimiento, model.NivelFidelizacion);
                hostal.AltaUsuario(huesped);
                return RedirectToAction("Login", "Login");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(model);
            }


        }

        [Privado(Roles = "huesped")]
        public IActionResult ListarAgendasDelHuesped(string email)
        {
            var listaAgendas = Hostal.Instancia.ListarAgendasOrdenadasPorFecha();
            var listaAgendasViewModel = new List<AgendaViewModel>();
            
            foreach (var agenda in listaAgendas)
            {
                if (agenda._huesped.Email == email)
                {
                    if(agenda._actividad.Fecha >= DateTime.Today)
                    {
                        var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);

                        listaAgendasViewModel.Add(agendaModel);

                    }

                }
            }

            return View(listaAgendasViewModel);
        }


       [Privado(Roles = "huesped")]
        public IActionResult ListarDatosHuesped(string email)
        {
            var huesped = Hostal.Instancia.ObtenerHuespedPorEmail(email);
            
            List<HuespedViewModel> datosHuesped = new List<HuespedViewModel>();

            if (huesped.Email == email)
            {
                datosHuesped.Add(new HuespedViewModel() {
                    Email = huesped.Email,
                    TipoDocumento = huesped._tipoDocumento,
                    NumeroDocumento = huesped.NumeroDocumento,
                    Nombre = huesped.Nombre,
                    Apellido = huesped.Apellido,
                    Habitacion = huesped.Habitacion,
                    FechaNacimiento = huesped.FechaNacimiento,
                    NivelFidelizacion = huesped.NivelFidelizacion
                });
            }

            return View(datosHuesped);
        }


    }
}

Obligatorio_P2_MVC/Views/Huesped/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Huéspedes</h1>

<div class="class = "btn btn-primary"">
    <a href="@Url.Action("ListarActividadesPorFecha", "Actividad")" class="btn btn-primary">Listar actividades por fecha</a>
    @Html.ActionLink("Listar Datos Huesped", "ListarDatosHuesped", "Huesped", new {email = Context.Session.GetString("email")}, new { @class = "btn btn-primary" })
    @Html.ActionLink("Listar agendas", "ListarAgendasDelHuesped", "Huesped", new {email = Context.Session.GetString("email")}, new { @class = "btn btn-primary" })  

</div>

Obligatorio_P2_MVC/Views/Huesped/ListarAgendasDelHuesped.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.AgendaViewModel>

@{
    ViewData["Title"] = "ListarAgendasDelHuesped";
}

<h1>Listar agendas de huésped</h1>

<table class="table">
<h3 class="alert-danger">@ViewBag.Error</h3>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Actividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaActividad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lugar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoActividad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Actividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaActividad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lugar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostoActividad)
            </td>
        </tr>
}
    </tbody>
</table>
                <p>
                    <a asp-action="Index" asp-controller="Huesped">Volver</a>
                </p>

Obligatorio_P2_MVC/Views/Huesped/ListarDatosHuesped.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.HuespedViewModel>

@{
    ViewData["Title"] = "ListarDatosHuesped";
}

<h1>Listar datos huésped</h1>

<table class="table">
<h3 class="alert-danger">@ViewBag.Error</h3>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraseña)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoDocumento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroDocumento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Habitacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NivelFidelizacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contraseña)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroDocumento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Habitacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NivelFidelizacion)
            </td>
           
        </tr>
}
    </tbody>
</table>
        <p>
            <a asp-action="Index" asp-controller="huesped">Volver a menú</a>
        </p>

Obligatorio_P2_MVC/Views/Huesped/RegistroHuesped.cshtml
@model Obligatorio_P2_MVC.Models.HuespedViewModel

@{
    ViewData["Title"] = "RegistroHuesped";
}

<h1>Registrar huésped</h1>

<div class="row">
    <h3 class="alert-danger">@ViewBag.Error</h3>
    <div class="col-md-4">
        <form asp-action="RegistroHuesped">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input asp-for="Contraseña" class="form-control" type="password" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDocumento" class="control-label"></label>
                <input asp-for="TipoDocumento" class="form-control" />
                <span asp-validation-for="TipoDocumento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroDocumento" class="control-label"></label>
                <input asp-for="NumeroDocumento" class="form-control" />
                <span asp-validation-for="NumeroDocumento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Habitacion" class="control-label"></label>
                <input asp-for="Habitacion" class="form-control" />
                <span asp-validation-for="Habitacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NivelFidelizacion" class="control-label"></label>
                <input asp-for="NivelFidelizacion" class="form-control" value="1" />
                <span asp-validation-for="NivelFidelizacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Registrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}