Obligatorio_P2_MVC/Models/ActividadViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Obligatorio_P2_MVC.Models
{
    public class ActividadViewModel
    {
       
        public int Id { get; set; }
        public string Nombre { get; set; }
        [DisplayName("Descripción")]
        public string Descripcion { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public DateTime Fecha { get; set; }
        [DisplayName("Cupo Máximo")]
        public int CupoMaximo { get; set; }
        [DisplayName("Edad Mínima")]
        public int EdadMinima { get; set; }
        [DisplayName("Costo ($U)")]
        public decimal CostoActividad { get; set; }

    }
}

Obligatorio_P2_MVC/Controllers/ActividadController.cs
using Microsoft.AspNetCore.Mvc;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Models;
using System.Reflection;

namespace Obligatorio_P2_MVC.Controllers
{
    public class ActividadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


      //  [Privado(Roles ="huesped, operador")]
        public IActionResult ListarActividadesPorFecha()
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == DateTime.Today)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
            }
            return View(listaActividades);
        }



        [HttpPost]
       // [Privado(Roles = "huesped, operador")]
        public IActionResult ListarActividadesPorFecha(DateTime fecha)
        {
            Hostal hostal = Hostal.Instancia;
            List<ActividadViewModel> listaActividades = new List<ActividadViewModel>();           

            foreach (var actividad in hostal.ObtenerActividades())
            {
                if (actividad.Fecha == fecha)
                {
                    listaActividades.Add(new ActividadViewModel() { Id = actividad.Id, Nombre = actividad.Nombre, Descripcion = actividad.Descripcion, Fecha = actividad.Fecha, CupoMaximo = actividad.CantidadMaximaDePersonas, EdadMinima = actividad.EdadMinimaRequerida, CostoActividad = actividad.CostoDeActividad });
                }
                if (listaActividades.Count == 0)
                {
                    ViewBag.Error = "No hay actividades en esa fecha";
                    
                }
            }
            return View(listaActividades);
        }

    }
}

Obligatorio_P2_MVC/Controllers/AgendaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Obligatorio_P2_MVC.Filters;
using Obligatorio_P2_MVC.Models;
using ObligatorioP2_C_;
using System.Reflection;
using Obligatorio_P2_MVC.Helpers;

namespace Obligatorio_P2_MVC.Controllers
{
    [Privado(Roles = "huesped")]
    public class AgendaController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Session.GetString("rol");
            if (HttpContext.Session.GetString("rol")== "huesped")
            {
               return RedirectToAction("Index", "Huesped");
            }
            else
            {
                return RedirectToAction("Index", "Operador");
            }
            
        }

        
        public IActionResult Agendar(int IdActividad)
        {   
            var huesped = Hostal.Instancia.ObtenerHuespedPorEmail(HttpContext.Session.GetString("email"));
            var actividad = Hostal.Instancia.ObtenerActividad(IdActividad);            
            var agenda = new Agenda(huesped, actividad);           
            
            Hostal.Instancia.AltaAgenda(agenda);

            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Los datos del formulario no son válidos.";
                return View("ListarActividadesPorFecha", "Actividad");
            }
            var agendaModel = AgendaViewModelMetodo.CrearAgendaViewModel(agenda);
            ViewBag.ActividadId = IdActividad;
            return View(agendaModel);
        }

        





    }
}

Obligatorio_P2_MVC/Views/Actividad/ListarActividadesPorFecha.cshtml
@model IEnumerable<Obligatorio_P2_MVC.Models.ActividadViewModel>

@{
    ViewData["Title"] = "ListarActividadesPorFecha";
}

<h1>Actividades por fecha</h1>
<form method="post" action="/Actividad/ListarActividadesPorFecha" class="m-lg-auto">
    <label for="fecha">Fecha:</label>
    <input type="date" id="fecha" name="fecha" required>
    <button type="submit" class="btn-primary">Buscar</button>
</form>

    <h3 class="alert-danger">@ViewBag.Error</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CupoMaximo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EdadMinima)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostoActividad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
       
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Fecha)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CupoMaximo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EdadMinima)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostoActividad)
                    </td>
                    <td>
                        @Html.ActionLink("Agendar", "Agendar", "Agenda", new {IdActividad =item.Id})
                    </td>
                </tr>
            }
        
        

     
            
    </tbody>
</table>
                 @Html.ActionLink("Volver", "Index", "Agenda")